dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - xlrd
    - openpyxl
    - XlsxWriter
    - Requests
    - lxml
    - html5lib
    - seaborn
    - plotly
    - statsmodels
